; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = FW_ALPHA_OLED
;default_envs = DEBUG
;default_envs = FW_GPS_SH1107_TYP2
;default_envs = FW_GPS_DOGS102_TYP2

src_dir = ./src/SmartDisplay/
build_dir = ./build/
;src_dir = src/fiz-o-matic

[env]

lib_deps =
	olikraus/U8g2@^2.28.8
	sandeepmistry/CAN@^0.3.1
	mikalhart/TinyGPSPlus@^1.0.2
	paulstoffregen/OneWire@^2.3.6
	milesburton/DallasTemperature@^3.9.1


[env:DEBUG]
platform = atmelmegaavr
framework = arduino

; Chip in use
board = ATmega4808
; Clock frequency in [Hz]
board_build.f_cpu = 16000000L
; Oscillator type (internal or external)
board_hardware.oscillator = internal
; Arduino pinout variant
board_build.variant = 32pin-standard

; Extra build flags
build_flags = -w -Os -DDEBUG -DSW_CAN -DSH1107

; Upload protocol for serial uploads (using Optiboot)
upload_protocol = arduino
upload_flags =
upload_port = /dev/cu.usbserial*

[env:DEBUG2]
platform = atmelmegaavr
board = ATmega4809
;platform = atmelavr
;board = uno
framework = arduino
;build_flags = -w -DDEBUG -DSW_CAN -DSH1106
;build_flags = -w -DDEBUG
build_flags = -w -Os -DSW_CAN -DSH1107_M32
;build_flags = -w

;EA Programm

[env:FW_ALPHA_OLED]
platform = atmelavr
board = uno
framework = arduino
build_flags = -w -Os -DHW_ALPHA_OLED

[env:FW_ALPHA_LCD]
platform = atmelavr
board = uno
framework = arduino
build_flags = -w -Os -DHW_ALPHA_LCD


[env:FW_CAN_SH1106_TYP2]
platform = atmelavr
board = uno
framework = arduino
build_flags = -w -DSW_CAN -DSH1106

[env:FW_GPS_SH1106_TYP2]
platform = atmelavr
board = uno
framework = arduino
build_flags = -w -DSW_GPS -DSH1106

[env:FW_GPS_DOGS102_TYP2]
platform = atmelavr
board = uno
framework = arduino
build_flags = -w -DSW_GPS -DDOGS102_T25

[env:FW_CAN_SH1107_TYP2]
platform = atmelavr
board = uno
framework = arduino
build_flags = -w -DSW_CAN -DSH1107

[env:FW_GPS_SH1107_TYP2]
platform = atmelavr
board = uno
framework = arduino
build_flags = -w -DSW_GPS -DSH1107

[env:FW_CAN_DOGS102_TYP2]
platform = atmelavr
board = uno
framework = arduino
build_flags = -w -DSW_CAN -DDOGS102_T25